version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  tests:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10"
    steps:
      - checkout
      - echo "Running unit function tests..."
      - run: python3 test_main.py

  deploy: 
    docker:
      - image: "circleci/python:3.10"
    steps:
      - echo "All tests passed. Deploying to Heroku."
      - heroku/deploy-via-git

workflows:
  tests_and_deploy:
    jobs:
      - tests
      - deploy:
          requires:
            - test