version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  tests:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10"
    steps:
      - checkout
      - run: echo "Running unit function tests..."
      - run: python3 main.py

  deploy: 
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git

workflows:
  tests_and_deploy:
    jobs:
      - tests
      - deploy:
          requires:
            - tests